### ISSUE TITLE
Unlisted requirements

### ISSUE THREAD

**Issue by jatentaki** [ducha-aiki/pyransac#1]
Hello, when trying to install (build) pyransac on xubuntu 18.04 LTS I got errors due to unmet requirements which are not listed in your README. Firstly it was fortran compiler

```
The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:18 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
```
then BLAS
```
CMake Error at /snap/cmake/177/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /snap/cmake/177/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /snap/cmake/177/share/cmake-3.16/Modules/FindBLAS.cmake:806 (find_package_handle_standard_args)
  /snap/cmake/177/share/cmake-3.16/Modules/FindLAPACK.cmake:197 (find_package)
  CMakeLists.txt:19 (FIND_PACKAGE)
```

I suggest those dependencies are added to README so that it doesn't look like a bug.

**Comment by ducha-aiki** [comment]
Thanks for the catch! I`ve added LAPACK just now

**Comment by Infinity8sailor** [comment]
i have lapack 
still shows `Could NOT find BLAS (missing: BLAS_LIBRARIES)` error

**Comment by ducha-aiki** [comment]
Added, thanks. I thought that LAPACK installs BLAS automatically, that is not the case. Thanks for the catch

http://www.netlib.org/lapack/faq.html#_why_aren_8217_t_blas_routines_included_when_i_download_an_lapack_routine
