### ISSUE TITLE
how to get inliners

### ISSUE THREAD

**Issue by InstantWindy** [ducha-aiki/pyransac#6]
Hi. How to get the coordinates of interior point? Thanks.

**Comment by ducha-aiki** [comment]
What do you mean by "interior" points?
If just inliers, then pyransac outputs mask. So just apply the mask to the input correspondences:

```python
H, mask = pyransac.findHomography(src_pts, dst_pts, th, 0.99, n_iter)
src_pts_inl = src_pts[mask]
dst_pts_inl = dst_pts[mask]
```

https://github.com/ducha-aiki/pyransac/blob/master/examples/simple-example.ipynb

Basically, the interface is the same as for opencv

**Comment by InstantWindy** [comment]
Thanks
